# Generated by Django 5.2.4 on 2025-08-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
