# Generated by Django 5.2.4 on 2025-08-09 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_created_cart_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_emission_factor_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fallback kg CO₂e per unit if product value not provided', max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='carbon_footprint_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Specific kg CO₂e per unit; leave blank to use category default', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ethics_score',
            field=models.PositiveIntegerField(default=50, help_text='0-100 composite ethics score'),
        ),
        migrations.AddField(
            model_name='product',
            name='impact_confidence',
            field=models.PositiveIntegerField(default=80, help_text='Confidence in impact data (0-100)'),
        ),
        migrations.CreateModel(
            name='OrderImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbon_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('baseline_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saved_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact', to='shop.order')),
            ],
        ),
        migrations.CreateModel(
            name='UserImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_carbon_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_saved_kg', models.DecimalField(decimal_places=2, default=0, help_text='Baseline - actual cumulative', max_digits=12)),
                ('current_month_carbon_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('month_budget_kg', models.DecimalField(decimal_places=2, default=0, help_text='User-set monthly carbon budget', max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact_summary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
