# Generated by Django 5.2.4 on 2025-08-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_courier_service_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100, unique=True)),
                ('co2_per_unit', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit_label', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🌳', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='badge',
            name='category',
            field=models.CharField(choices=[('CARBON', 'Carbon Reduction'), ('GENERAL', 'General Achievement'), ('STREAK', 'Streak Achievement'), ('MILESTONE', 'Milestone Achievement')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='badge',
            name='icon',
            field=models.CharField(default='🌱', max_length=50),
        ),
        migrations.AddField(
            model_name='badge',
            name='popup_message',
            field=models.TextField(blank=True),
        ),
    ]
